"""add interviews table

Revision ID: 3766354ddc7c
Revises: 20251014_0000
Create Date: 2025-10-18 19:22:34.460451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3766354ddc7c'
down_revision: Union[str, None] = '20251014_0000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.String(length=50), nullable=False),
    sa.Column('student_id', sa.String(length=50), nullable=False),
    sa.Column('admin_id', sa.String(length=50), nullable=False),
    sa.Column('admission_cycle_id', sa.String(length=50), nullable=False),
    sa.Column('interview_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('interview_link', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'COMPLETED', 'CANCELLED', name='interviewstatusenum'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admin_users.admin_id'], ),
    sa.ForeignKeyConstraint(['admission_cycle_id'], ['admission_cycles.cycle_id'], ),
    sa.ForeignKeyConstraint(['application_id'], ['applications.application_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student_accounts.student_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id')
    )
    op.create_index('idx_interview_admin_cycle', 'interviews', ['admin_id', 'admission_cycle_id'], unique=False)
    op.create_index('idx_interview_status_time', 'interviews', ['status', 'interview_time'], unique=False)
    op.create_index('idx_interview_student_cycle', 'interviews', ['student_id', 'admission_cycle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_interview_student_cycle', table_name='interviews')
    op.drop_index('idx_interview_status_time', table_name='interviews')
    op.drop_index('idx_interview_admin_cycle', table_name='interviews')
    op.drop_table('interviews')
    # ### end Alembic commands ###
