"""add_bias_monitoring_tables

Revision ID: 96eed8915a45
Revises: 3766354ddc7c
Create Date: 2025-10-19 11:54:35.689299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '96eed8915a45'
down_revision: Union[str, None] = '3766354ddc7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_bias_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('admin_id', sa.String(length=50), nullable=False),
    sa.Column('total_interviews_conducted', sa.Integer(), nullable=False),
    sa.Column('total_bias_incidents', sa.Integer(), nullable=False),
    sa.Column('total_blocks_received', sa.Integer(), nullable=False),
    sa.Column('current_status', sa.Enum('ACTIVE', 'WARNED', 'SUSPENDED', 'BANNED', name='adminbiasstatusenum'), nullable=False),
    sa.Column('suspension_count', sa.Integer(), nullable=False),
    sa.Column('last_incident_date', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('strikes', sa.Integer(), nullable=False),
    sa.Column('strike_reset_date', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admin_users.admin_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('admin_id')
    )
    op.create_index('idx_bias_history_status', 'admin_bias_history', ['current_status'], unique=False)
    op.create_table('drift_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('admin_id', sa.String(length=50), nullable=False),
    sa.Column('admission_cycle_id', sa.String(length=50), nullable=True),
    sa.Column('period_start', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('period_end', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('total_interviews', sa.Integer(), nullable=False),
    sa.Column('bias_incidents', sa.Integer(), nullable=False),
    sa.Column('nudges_delivered', sa.Integer(), nullable=False),
    sa.Column('warnings_delivered', sa.Integer(), nullable=False),
    sa.Column('blocks_triggered', sa.Integer(), nullable=False),
    sa.Column('avg_score_given', sa.Float(), nullable=True),
    sa.Column('score_variance', sa.Float(), nullable=True),
    sa.Column('harsh_outlier_count', sa.Integer(), nullable=False),
    sa.Column('lenient_outlier_count', sa.Integer(), nullable=False),
    sa.Column('irr_correlation', sa.Float(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('calculated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admin_users.admin_id'], ),
    sa.ForeignKeyConstraint(['admission_cycle_id'], ['admission_cycles.cycle_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_drift_admin', 'drift_metrics', ['admin_id', 'period_end'], unique=False)
    op.create_table('bias_flags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('interview_id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.String(length=50), nullable=False),
    sa.Column('application_id', sa.String(length=50), nullable=True),
    sa.Column('flag_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.Enum('NONE', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severityenum'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('action_taken', sa.String(length=50), nullable=False),
    sa.Column('automatic', sa.Boolean(), nullable=False),
    sa.Column('reviewed', sa.Boolean(), nullable=False),
    sa.Column('reviewed_by', sa.String(length=50), nullable=True),
    sa.Column('reviewed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admin_users.admin_id'], ),
    sa.ForeignKeyConstraint(['application_id'], ['applications.application_id'], ),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['admin_users.admin_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_flags_admin', 'bias_flags', ['admin_id', 'created_at'], unique=False)
    op.create_index('idx_flags_review', 'bias_flags', ['reviewed', 'severity'], unique=False)
    op.create_table('live_transcripts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('interview_id', sa.Integer(), nullable=False),
    sa.Column('speaker', sa.Enum('ADMIN', 'STUDENT', name='speakerenum'), nullable=False),
    sa.Column('transcript_text', sa.Text(), nullable=False),
    sa.Column('start_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('end_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_transcripts_interview', 'live_transcripts', ['interview_id', 'start_time'], unique=False)
    op.create_table('live_bias_analysis',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transcript_id', sa.Integer(), nullable=False),
    sa.Column('interview_id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.String(length=50), nullable=False),
    sa.Column('bias_detected', sa.Boolean(), nullable=False),
    sa.Column('bias_types', sa.JSON(), nullable=True),
    sa.Column('severity', sa.Enum('NONE', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severityenum'), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('evidence_quotes', sa.JSON(), nullable=True),
    sa.Column('context_summary', sa.Text(), nullable=True),
    sa.Column('recommended_action', sa.Enum('NONE', 'NUDGE', 'WARN', 'BLOCK', name='recommendedactionenum'), nullable=False),
    sa.Column('llm_model', sa.String(length=50), nullable=False),
    sa.Column('llm_response_raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('analyzed_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admin_users.admin_id'], ),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ),
    sa.ForeignKeyConstraint(['transcript_id'], ['live_transcripts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_analysis_admin', 'live_bias_analysis', ['admin_id', 'analyzed_at'], unique=False)
    op.create_index('idx_analysis_interview', 'live_bias_analysis', ['interview_id', 'analyzed_at'], unique=False)
    op.create_table('live_nudges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('interview_id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.String(length=50), nullable=False),
    sa.Column('nudge_type', sa.Enum('INFO', 'WARNING', 'BLOCK', name='nudgetypeenum'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('display_duration', sa.Integer(), nullable=True),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.Column('acknowledged_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('dismissed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admin_users.admin_id'], ),
    sa.ForeignKeyConstraint(['analysis_id'], ['live_bias_analysis.id'], ),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_nudges_interview', 'live_nudges', ['interview_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_nudges_interview', table_name='live_nudges')
    op.drop_table('live_nudges')
    op.drop_index('idx_analysis_interview', table_name='live_bias_analysis')
    op.drop_index('idx_analysis_admin', table_name='live_bias_analysis')
    op.drop_table('live_bias_analysis')
    op.drop_index('idx_transcripts_interview', table_name='live_transcripts')
    op.drop_table('live_transcripts')
    op.drop_index('idx_flags_review', table_name='bias_flags')
    op.drop_index('idx_flags_admin', table_name='bias_flags')
    op.drop_table('bias_flags')
    op.drop_index('idx_drift_admin', table_name='drift_metrics')
    op.drop_table('drift_metrics')
    op.drop_index('idx_bias_history_status', table_name='admin_bias_history')
    op.drop_table('admin_bias_history')
    # ### end Alembic commands ###
