"""add interview scores table

Revision ID: 43ce10edf815
Revises: 0c5810f251cb
Create Date: 2025-10-19 12:49:34.983684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43ce10edf815'
down_revision: Union[str, None] = '0c5810f251cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('interview_id', sa.Integer(), nullable=False),
    sa.Column('communication_score', sa.Float(), nullable=False),
    sa.Column('critical_thinking_score', sa.Float(), nullable=False),
    sa.Column('motivation_score', sa.Float(), nullable=False),
    sa.Column('final_interview_score', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('scored_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('scored_by', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ),
    sa.ForeignKeyConstraint(['scored_by'], ['admin_users.admin_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('interview_id')
    )
    op.create_index('idx_interview_score_final', 'interview_scores', ['final_interview_score'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_interview_score_final', table_name='interview_scores')
    op.drop_table('interview_scores')
    # ### end Alembic commands ###
