"""Add student OAuth tables and application FK

Revision ID: 20251014_0000
Revises: e2354a7dd801
Create Date: 2025-10-14 12:00:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "20251014_0000"
down_revision: Union[str, None] = "e2354a7dd801"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


studentstatusenum = sa.Enum("active", "suspended", "deleted", name="studentstatusenum")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # studentstatusenum.create(op.get_bind(), checkfirst=True)

    op.create_table(
        "student_accounts",
        sa.Column("student_id", sa.String(length=50), nullable=False),
        sa.Column("primary_email", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=True),
        sa.Column("status", studentstatusenum, nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("verified_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("student_id"),
        sa.UniqueConstraint("primary_email"),
    )
    op.create_index("idx_student_status", "student_accounts", ["status"], unique=False)

    op.create_table(
        "student_auth_states",
        sa.Column("state", sa.String(length=64), nullable=False),
        sa.Column("code_challenge", sa.String(length=128), nullable=False),
        sa.Column("code_verifier_hash", sa.String(length=128), nullable=False),
        sa.Column("nonce", sa.String(length=64), nullable=True),
        sa.Column("redirect_uri", sa.Text(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("expires_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("consumed", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("state"),
    )
    op.create_index("idx_auth_state_expires", "student_auth_states", ["expires_at"], unique=False)

    op.create_table(
        "oauth_identities",
        sa.Column("identity_id", sa.Integer(), nullable=False),
        sa.Column("student_id", sa.String(length=50), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("provider_sub", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("email_verified", sa.Boolean(), nullable=False),
        sa.Column("raw_profile", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["student_id"], ["student_accounts.student_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("identity_id"),
        sa.UniqueConstraint("provider", "provider_sub", name="uq_oauth_provider_sub"),
    )
    op.create_index("idx_oauth_student", "oauth_identities", ["student_id"], unique=False)

    op.create_table(
        "student_sessions",
        sa.Column("session_id", sa.String(length=64), nullable=False),
        sa.Column("student_id", sa.String(length=50), nullable=False),
        sa.Column("session_token_hash", sa.String(length=128), nullable=False),
        sa.Column("expires_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("last_active_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("revoked", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["student_id"], ["student_accounts.student_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("session_id"),
        sa.UniqueConstraint("session_token_hash"),
    )
    op.create_index("idx_student_session_student", "student_sessions", ["student_id"], unique=False)
    op.create_index("idx_student_session_token", "student_sessions", ["session_token_hash"], unique=False)

    op.add_column("applications", sa.Column("student_id", sa.String(length=50), nullable=True))
    op.create_unique_constraint(
        "uq_application_student_cycle",
        "applications",
        ["student_id", "admission_cycle_id"],
    )
    op.create_foreign_key(
        "applications_student_id_fkey",
        "applications",
        "student_accounts",
        ["student_id"],
        ["student_id"],
        ondelete="SET NULL",
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("applications_student_id_fkey", "applications", type_="foreignkey")
    op.drop_constraint("uq_application_student_cycle", "applications", type_="unique")
    op.drop_column("applications", "student_id")

    op.drop_index("idx_student_session_token", table_name="student_sessions")
    op.drop_index("idx_student_session_student", table_name="student_sessions")
    op.drop_table("student_sessions")

    op.drop_index("idx_oauth_student", table_name="oauth_identities")
    op.drop_table("oauth_identities")

    op.drop_index("idx_auth_state_expires", table_name="student_auth_states")
    op.drop_table("student_auth_states")

    op.drop_index("idx_student_status", table_name="student_accounts")
    op.drop_table("student_accounts")

    studentstatusenum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###

