"""Initial migration

Revision ID: 3593d09278ec
Revises: 
Create Date: 2025-10-12 03:05:54.504006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3593d09278ec'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('admin_id', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'SUPER_ADMIN', 'AUDITOR', name='adminroleenum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('last_login', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('admin_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index('idx_admin_email', 'admin_users', ['email'], unique=False)
    op.create_index('idx_admin_username', 'admin_users', ['username'], unique=False)
    op.create_table('audit_logs',
    sa.Column('log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=False),
    sa.Column('action', sa.Enum('CREATE', 'UPDATE', 'DELETE', 'EVALUATE', 'FINALIZE', 'SELECT', 'PUBLISH', 'LOGIN', 'LOGOUT', name='auditactionenum'), nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('log_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('previous_hash', sa.String(length=64), nullable=True),
    sa.Column('current_hash', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index('idx_audit_actor', 'audit_logs', ['actor'], unique=False)
    op.create_index('idx_audit_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index('idx_audit_timestamp', 'audit_logs', ['timestamp'], unique=False)
    op.create_table('admin_sessions',
    sa.Column('session_id', sa.String(length=50), nullable=False),
    sa.Column('admin_id', sa.String(length=50), nullable=False),
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admin_users.admin_id'], ),
    sa.PrimaryKeyConstraint('session_id'),
    sa.UniqueConstraint('token')
    )
    op.create_index('idx_session_admin_expires', 'admin_sessions', ['admin_id', 'expires_at'], unique=False)
    op.create_index('idx_session_token', 'admin_sessions', ['token'], unique=False)
    op.create_table('admission_cycles',
    sa.Column('cycle_id', sa.String(length=50), nullable=False),
    sa.Column('cycle_name', sa.String(length=100), nullable=False),
    sa.Column('phase', sa.Enum('SUBMISSION', 'FROZEN', 'PREPROCESSING', 'BATCH_PREP', 'PROCESSING', 'SCORED', 'SELECTION', 'PUBLISHED', 'COMPLETED', name='admissionphaseenum'), nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('max_seats', sa.Integer(), nullable=False),
    sa.Column('current_seats', sa.Integer(), nullable=False),
    sa.Column('selected_count', sa.Integer(), nullable=False),
    sa.Column('result_date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('start_date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('end_date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('closed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('closed_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['closed_by'], ['admin_users.admin_id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['admin_users.admin_id'], ),
    sa.PrimaryKeyConstraint('cycle_id')
    )
    op.create_index('idx_cycle_dates', 'admission_cycles', ['start_date', 'end_date'], unique=False)
    op.create_index('idx_cycle_open_phase', 'admission_cycles', ['is_open', 'phase'], unique=False)
    op.create_table('applications',
    sa.Column('application_id', sa.String(length=50), nullable=False),
    sa.Column('admission_cycle_id', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('gpa', sa.Float(), nullable=False),
    sa.Column('test_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('essay', sa.Text(), nullable=False),
    sa.Column('achievements', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('SUBMITTED', 'FINALIZED', 'PREPROCESSING', 'BATCH_READY', 'PROCESSING', 'SCORED', 'SELECTED', 'NOT_SELECTED', 'PUBLISHED', 'FAILED', name='applicationstatusenum'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['admission_cycle_id'], ['admission_cycles.cycle_id'], ),
    sa.PrimaryKeyConstraint('application_id')
    )
    op.create_index('idx_app_cycle_status', 'applications', ['admission_cycle_id', 'status'], unique=False)
    op.create_index('idx_app_email', 'applications', ['email'], unique=False)
    op.create_index('idx_app_id', 'applications', ['application_id'], unique=False)
    op.create_table('batch_runs',
    sa.Column('batch_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('admission_cycle_id', sa.String(length=50), nullable=False),
    sa.Column('batch_type', sa.Enum('WORKER_EVALUATION', 'JUDGE_REVIEW', name='batchtypeenum'), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('input_file_path', sa.Text(), nullable=False),
    sa.Column('output_file_path', sa.Text(), nullable=True),
    sa.Column('total_records', sa.Integer(), nullable=False),
    sa.Column('processed_records', sa.Integer(), nullable=False),
    sa.Column('failed_records', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='batchstatusenum'), nullable=False),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('triggered_by', sa.String(length=50), nullable=False),
    sa.Column('error_log', sa.Text(), nullable=True),
    sa.Column('batch_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['admission_cycle_id'], ['admission_cycles.cycle_id'], ),
    sa.ForeignKeyConstraint(['triggered_by'], ['admin_users.admin_id'], ),
    sa.PrimaryKeyConstraint('batch_id')
    )
    op.create_index('idx_batch_cycle_type', 'batch_runs', ['admission_cycle_id', 'batch_type'], unique=False)
    op.create_index('idx_batch_status_started', 'batch_runs', ['status', 'started_at'], unique=False)
    op.create_table('selection_logs',
    sa.Column('selection_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('admission_cycle_id', sa.String(length=50), nullable=False),
    sa.Column('program_name', sa.String(length=100), nullable=True),
    sa.Column('selected_count', sa.Integer(), nullable=False),
    sa.Column('selection_criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cutoff_score', sa.Float(), nullable=False),
    sa.Column('executed_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('executed_by', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['admission_cycle_id'], ['admission_cycles.cycle_id'], ),
    sa.ForeignKeyConstraint(['executed_by'], ['admin_users.admin_id'], ),
    sa.PrimaryKeyConstraint('selection_id')
    )
    op.create_index('idx_selection_cycle', 'selection_logs', ['admission_cycle_id'], unique=False)
    op.create_table('anonymized_applications',
    sa.Column('anonymized_id', sa.String(length=50), nullable=False),
    sa.Column('application_id', sa.String(length=50), nullable=False),
    sa.Column('gpa', sa.Float(), nullable=False),
    sa.Column('test_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('essay_scrubbed', sa.Text(), nullable=False),
    sa.Column('achievements_scrubbed', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.application_id'], ),
    sa.PrimaryKeyConstraint('anonymized_id'),
    sa.UniqueConstraint('application_id')
    )
    op.create_index('idx_anon_app_id', 'anonymized_applications', ['application_id'], unique=False)
    op.create_table('deterministic_metrics',
    sa.Column('metric_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.String(length=50), nullable=False),
    sa.Column('test_average', sa.Float(), nullable=False),
    sa.Column('academic_score_computed', sa.Float(), nullable=False),
    sa.Column('percentile_rank', sa.Float(), nullable=True),
    sa.Column('computed_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.application_id'], ),
    sa.PrimaryKeyConstraint('metric_id'),
    sa.UniqueConstraint('application_id')
    )
    op.create_index('idx_metrics_app_id', 'deterministic_metrics', ['application_id'], unique=False)
    op.create_table('final_scores',
    sa.Column('score_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('anonymized_id', sa.String(length=50), nullable=False),
    sa.Column('final_score', sa.Float(), nullable=False),
    sa.Column('academic_score', sa.Float(), nullable=False),
    sa.Column('test_score', sa.Float(), nullable=False),
    sa.Column('achievement_score', sa.Float(), nullable=False),
    sa.Column('essay_score', sa.Float(), nullable=False),
    sa.Column('llm_score', sa.Float(), nullable=True),
    sa.Column('llm_explanation', sa.Text(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('strengths', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('areas_for_improvement', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=True),
    sa.Column('worker_attempts', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('SUBMITTED', 'FINALIZED', 'PREPROCESSING', 'BATCH_READY', 'PROCESSING', 'SCORED', 'SELECTED', 'NOT_SELECTED', 'PUBLISHED', 'FAILED', name='applicationstatusenum'), nullable=False),
    sa.ForeignKeyConstraint(['anonymized_id'], ['anonymized_applications.anonymized_id'], ),
    sa.PrimaryKeyConstraint('score_id'),
    sa.UniqueConstraint('anonymized_id')
    )
    op.create_index('idx_final_anon', 'final_scores', ['anonymized_id'], unique=False)
    op.create_index('idx_final_status', 'final_scores', ['status'], unique=False)
    op.create_table('hash_chain',
    sa.Column('chain_id', sa.String(length=50), nullable=False),
    sa.Column('anonymized_id', sa.String(length=50), nullable=False),
    sa.Column('decision_type', sa.String(length=100), nullable=False),
    sa.Column('data_json', sa.Text(), nullable=False),
    sa.Column('data_hash', sa.String(length=64), nullable=False),
    sa.Column('previous_hash', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['anonymized_id'], ['anonymized_applications.anonymized_id'], ),
    sa.PrimaryKeyConstraint('chain_id')
    )
    op.create_index('idx_hash_anon', 'hash_chain', ['anonymized_id'], unique=False)
    op.create_index('idx_hash_timestamp', 'hash_chain', ['timestamp'], unique=False)
    op.create_table('identity_mapping',
    sa.Column('mapping_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('anonymized_id', sa.String(length=50), nullable=False),
    sa.Column('application_id', sa.String(length=50), nullable=False),
    sa.Column('encrypted_pii', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['anonymized_id'], ['anonymized_applications.anonymized_id'], ),
    sa.ForeignKeyConstraint(['application_id'], ['applications.application_id'], ),
    sa.PrimaryKeyConstraint('mapping_id'),
    sa.UniqueConstraint('anonymized_id'),
    sa.UniqueConstraint('application_id')
    )
    op.create_index('idx_identity_anon', 'identity_mapping', ['anonymized_id'], unique=False)
    op.create_index('idx_identity_app', 'identity_mapping', ['application_id'], unique=False)
    op.create_table('worker_results',
    sa.Column('result_id', sa.String(length=50), nullable=False),
    sa.Column('anonymized_id', sa.String(length=50), nullable=False),
    sa.Column('batch_run_id', sa.Integer(), nullable=True),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('academic_score', sa.Float(), nullable=False),
    sa.Column('test_score', sa.Float(), nullable=False),
    sa.Column('achievement_score', sa.Float(), nullable=False),
    sa.Column('essay_score', sa.Float(), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('reasoning', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rubric_adherence', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['anonymized_id'], ['anonymized_applications.anonymized_id'], ),
    sa.ForeignKeyConstraint(['batch_run_id'], ['batch_runs.batch_id'], ),
    sa.PrimaryKeyConstraint('result_id')
    )
    op.create_index('idx_worker_anon_attempt', 'worker_results', ['anonymized_id', 'attempt_number'], unique=False)
    op.create_index('idx_worker_batch', 'worker_results', ['batch_run_id'], unique=False)
    op.create_table('judge_results',
    sa.Column('judge_id', sa.String(length=50), nullable=False),
    sa.Column('result_id', sa.String(length=50), nullable=False),
    sa.Column('anonymized_id', sa.String(length=50), nullable=False),
    sa.Column('worker_result_id', sa.String(length=50), nullable=False),
    sa.Column('batch_run_id', sa.Integer(), nullable=True),
    sa.Column('decision', sa.Enum('APPROVED', 'REJECTED', name='judgedecisionenum'), nullable=False),
    sa.Column('bias_detected', sa.Boolean(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['anonymized_id'], ['anonymized_applications.anonymized_id'], ),
    sa.ForeignKeyConstraint(['batch_run_id'], ['batch_runs.batch_id'], ),
    sa.ForeignKeyConstraint(['worker_result_id'], ['worker_results.result_id'], ),
    sa.PrimaryKeyConstraint('judge_id')
    )
    op.create_index('idx_judge_batch', 'judge_results', ['batch_run_id'], unique=False)
    op.create_index('idx_judge_worker', 'judge_results', ['worker_result_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_judge_worker', table_name='judge_results')
    op.drop_index('idx_judge_batch', table_name='judge_results')
    op.drop_table('judge_results')
    op.drop_index('idx_worker_batch', table_name='worker_results')
    op.drop_index('idx_worker_anon_attempt', table_name='worker_results')
    op.drop_table('worker_results')
    op.drop_index('idx_identity_app', table_name='identity_mapping')
    op.drop_index('idx_identity_anon', table_name='identity_mapping')
    op.drop_table('identity_mapping')
    op.drop_index('idx_hash_timestamp', table_name='hash_chain')
    op.drop_index('idx_hash_anon', table_name='hash_chain')
    op.drop_table('hash_chain')
    op.drop_index('idx_final_status', table_name='final_scores')
    op.drop_index('idx_final_anon', table_name='final_scores')
    op.drop_table('final_scores')
    op.drop_index('idx_metrics_app_id', table_name='deterministic_metrics')
    op.drop_table('deterministic_metrics')
    op.drop_index('idx_anon_app_id', table_name='anonymized_applications')
    op.drop_table('anonymized_applications')
    op.drop_index('idx_selection_cycle', table_name='selection_logs')
    op.drop_table('selection_logs')
    op.drop_index('idx_batch_status_started', table_name='batch_runs')
    op.drop_index('idx_batch_cycle_type', table_name='batch_runs')
    op.drop_table('batch_runs')
    op.drop_index('idx_app_id', table_name='applications')
    op.drop_index('idx_app_email', table_name='applications')
    op.drop_index('idx_app_cycle_status', table_name='applications')
    op.drop_table('applications')
    op.drop_index('idx_cycle_open_phase', table_name='admission_cycles')
    op.drop_index('idx_cycle_dates', table_name='admission_cycles')
    op.drop_table('admission_cycles')
    op.drop_index('idx_session_token', table_name='admin_sessions')
    op.drop_index('idx_session_admin_expires', table_name='admin_sessions')
    op.drop_table('admin_sessions')
    op.drop_index('idx_audit_timestamp', table_name='audit_logs')
    op.drop_index('idx_audit_entity', table_name='audit_logs')
    op.drop_index('idx_audit_actor', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('idx_admin_username', table_name='admin_users')
    op.drop_index('idx_admin_email', table_name='admin_users')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
